version: "3.9"

services:
  dns_server:
    build: .
    volumes:
      - ./db.servicoa:/data/bind/db.servicoa
      - ./db.servicob:/data/bind/db.servicob
      - ./db.servicoc:/data/bind/db.servicoc
      - ./named.conf.local:/data/bind/named.conf.local 
      - ./named.conf.options:/data/bind/named.conf.options
    networks:
      app_net:
        ipv4_address: 172.16.0.10
  app:
    build: ./ruby/
    volumes:
      - ./named.conf.local:/data/bind/named.conf.local 
      - ./named.conf.options:/data/bind/named.conf.options
    networks:
      - app_net
    dns: 172.16.0.10
    ports:
      - "3000:3000"
 
networks:
    app_net:
      ipam:
        driver: default
        config:
          - subnet: "172.16.0.0/24"
          - subnet: "2001:3984:3989::/64"